### PR TITLE
Adding refactored temperature files to dev branch for integration with UI

### PR DESCRIPTION
**Pull request by Ishi01**
This merge contains the two files required for the data preprocessing portion of the project, simplified down to a form which should be easily to integrate with the UI and temperature inversion segments. It also includes a predraft of the method documentation for these files, though this will need revision.

Note that all of the test files were removed from this version, so if I can't cleanly solve the merge conficts this is probably going to cause I will figure something else out.

### CODE REVIEW

**Comment by Ishi01** [comment]
Merge conflicts resolved, all should be good to merge once Long and ideally someone else takes a look

**Comment by WWH987** [comment]
It looks good, I'll have a look at the files and figure out how to connect it with the UI, after that the PR is good to merge

**Review by LongQin0121 — COMMENTED** [review]
this   is good~~I will go to Jianguo for talking a bit about data preprocessing~it is still confusing~

**Comment by LongQin0121** [comment]
For the datapreprocessing, it is good to automate the process, but the whole flow could still be changed as the client is not sure about what they want 100% now.  gonna   give them some advises.

**Pull request merged**
