### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by simonli66666**
add some description of Readme

### CODE REVIEW

**Review by WWH987 — COMMENTED** [review]
OK

**Review by Hayeensss — APPROVED** [review]
Simon just added some descriptions for some input and output folders. Looks good to go. Others can review it see if there have any difference with your guys understanding.

**Comment by LongQin0121** [comment]
all good~

**Review by WWH987 — APPROVED** [review]

**Review by WWH987 — APPROVED** [review]
OK

**Review by LongQin0121 — APPROVED** [review]
Good

**Review by Hayeensss — APPROVED** [review]
All good with No new changes

**Pull request merged**
