### PR TITLE
Quick fatal fix

### PR DESCRIPTION
**Pull request by WWH987**
Fix on temp file selection error.

### CODE REVIEW

**Review by simonli66666 — APPROVED** [review]
looks good

**Comment by LongQin0121** [comment]
ALL  Good~~

**Review by LongQin0121 — APPROVED** [review]
Great~

**Review by Hayeensss — APPROVED** [review]
changes:
1. UI tab(window) name change
2. Add 3 exceptions handle
Looks good to go.

**Review by Aria622 — APPROVED** [review]
All good.

**Comment by WWH987** [comment]
**Key Change:** missing library caused failure to extract the temperature file from temp folder.

**Pull request merged**
