### PR TITLE
Water content Implementation

### PR DESCRIPTION
**Pull request by Hayeensss**
- Main code Implementation
- Unit Test
- Documentation

### CODE REVIEW

**Comment by Hayeensss** [comment]
Hi @Ishi01 I finished WaterContent part, added unit test, wrote a documentation for that. I passed test for all functions. Any features(parameters) if needed can add later.

**Comment by Ishi01** [comment]
Looks Amazing, well done!
Code is clean, efficient and well documented, documentation is thorough, clear and descriptive, testing suite is good, and code runs well without errors. IMO its good to merge into dev, though if anyone else wants to take a look before merge I'll leave the request for hayeen to merge later.

**Comment by WWH987** [comment]
Please merge the branch into dev for integration, this PR is closed, I'll shoot up a new PR

**Comment by Hayeensss** [comment]
image
As I said, I already merged `WaterContent` into `dev`.

**Pull request closed without merging**
