### PR TITLE
Dev to Main

### PR DESCRIPTION
**Pull request by LongQin0121**
This is from dev to main branch, as a **milestone** for our project.

### CODE REVIEW

**Comment by Aria622** [comment]
Looks all good.

**Review by WWH987 — COMMENTED** [review]
Looks good

**Review by Aria622 — APPROVED** [review]
Looks all good for me

**Review by Hayeensss — APPROVED** [review]
looks good to go. But no need to includes `[old_back-files]` this section in Main branch.

**Review by Ishi01 — APPROVED** [review]
With the bug fixes and corrections, this looks great for an initial prototype! I think it's ready to merge once everyone has a look at it.

**Comment by LongQin0121** [comment]
Thanks, We are gonna move on to the next step after the report2~

**Pull request merged**
